export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";

// Category.
export const READ_CATEGORY = "READ_CATEGORY";
export const READ_CATEGORY_PENDING = "READ_CATEGORY_PENDING";
export const READ_CATEGORY_SUCCESS = "READ_CATEGORY_SUCCESS";
export const READ_CATEGORY_FAILURE = "READ_CATEGORY_FAILURE";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_PENDING = "CREATE_CATEGORY_PENDING";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_PENDING = "UPDATE_CATEGORY_PENDING";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_PENDING = "DELETE_CATEGORY_PENDING";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

// end category

//comment 
export const READ_COMMENT = "READ_COMMENT";
export const READ_COMMENT_PENDING = "READ_COMMENT_PENDING";
export const READ_COMMENT_SUCCESS = "READ_COMMENT_SUCCESS";
export const READ_COMMENT_FAILURE = "READ_COMMENT_FAILURE";

export const CREATE_COMMENT = "CREATE_COMMENT";
export const CREATE_COMMENT_PENDING = "CREATE_COMMENT_PENDING";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";

export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const UPDATE_COMMENT_PENDING = "UPDATE_COMMENT_PENDING";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAILURE = "UPDATE_COMMENT_FAILURE";

export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_COMMENT_PENDING = "DELETE_COMMENT_PENDING";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";
//end comment 

//branch
export const READ_BRANCH = "READ_BRANCH";
export const READ_BRANCH_PENDING = "READ_BRANCH_PENDING";
export const READ_BRANCH_SUCCESS = "READ_BRANCH_SUCCESS";
export const READ_BRANCH_FAILURE = "READ_BRANCH_FAILURE";

export const CREATE_BRANCH = "CREATE_BRANCH";
export const CREATE_BRANCH_PENDING = "CREATE_BRANCH_PENDING";
export const CREATE_BRANCH_SUCCESS = "CREATE_BRANCH_SUCCESS";
export const CREATE_BRANCH_FAILURE = "CREATE_BRANCH_FAILURE";

export const UPDATE_BRANCH = "UPDATE_BRANCH";
export const UPDATE_BRANCH_PENDING = "UPDATE_BRANCH_PENDING";
export const UPDATE_BRANCH_SUCCESS = "UPDATE_BRANCH_SUCCESS";
export const UPDATE_BRANCH_FAILURE = "UPDATE_BRANCH_FAILURE";

export const DELETE_BRANCH = "DELETE_BRANCH";
export const DELETE_BRANCH_PENDING = "DELETE_BRANCH_PENDING";
export const DELETE_BRANCH_SUCCESS = "DELETE_BRANCH_SUCCESS";
export const DELETE_BRANCH_FAILURE = "DELETE_BRANCH_FAILURE";
//end branch

//user
export const READ_USER = "READ_USER";
export const READ_USER_PENDING = "READ_USER_PENDING";
export const READ_USER_SUCCESS = "READ_USER_SUCCESS";
export const READ_USER_FAILURE = "READ_USER_FAILURE";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_PENDING = "CREATE_USER_PENDING";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_PENDING = "UPDATE_USER_PENDING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_PENDING = "DELETE_USER_PENDING";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
//end user

// room 
export const READ_ROOM = "READ_ROOM";
export const READ_ROOM_PENDING = "READ_ROOM_PENDING";
export const READ_ROOM_SUCCESS = "READ_ROOM_SUCCESS";
export const READ_ROOM_FAILURE = "READ_ROOM_FAILURE";

export const CREATE_ROOM = "CREATE_ROOM";
export const CREATE_ROOM_PENDING = "CREATE_ROOM_PENDING";
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const CREATE_ROOM_FAILURE = "CREATE_ROOM_FAILURE";

export const UPDATE_ROOM = "UPDATE_ROOM";
export const UPDATE_ROOM_PENDING = "UPDATE_ROOM_PENDING";
export const UPDATE_ROOM_SUCCESS = "UPDATE_ROOM_SUCCESS";
export const UPDATE_ROOM_FAILURE = "UPDATE_ROOM_FAILURE";

export const DELETE_ROOM = "DELETE_ROOM";
export const DELETE_ROOM_PENDING = "DELETE_ROOM_PENDING";
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS";
export const DELETE_ROOM_FAILURE = "DELETE_ROOM_FAILURE";
// end room