export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";

// Category.
export const READ_CATEGORY = "READ_CATEGORY";
export const READ_CATEGORY_PENDING = "READ_CATEGORY_PENDING";
export const READ_CATEGORY_SUCCESS = "READ_CATEGORY_SUCCESS";
export const READ_CATEGORY_FAILURE = "READ_CATEGORY_FAILURE";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_PENDING = "CREATE_CATEGORY_PENDING";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_PENDING = "UPDATE_CATEGORY_PENDING";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_PENDING = "DELETE_CATEGORY_PENDING";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

// end category